apiVersion: v1
kind: Namespace
metadata:
  name: hello-world-namespace

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  namespace: hello-world-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world-container
          image: berkayquzel/hello-world-app-2  # Docker Hub'daki görüntü adınızı buraya ekleyin
          ports:
            - containerPort: 8084

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: hello-world-namespace
spec:
  selector:
    app: hello-world
  ports:
    - port: 80
      targetPort: 8084

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-ingress
  namespace: hello-world-namespace
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: hello-world-b.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: hello-world-service
                port:
                  number: 80
